services:
  eureka-server:
    image: psup-eureka/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - CONFIG_SERVER_URL=http://config-server:8888
      - CONFIG_SERVER_USERNAME=myUsername
      - CONFIG_SERVER_PASSWORD=mySecretPassword
    networks:
      - eureka-server-net
      - psup-shared-net

networks:
  eureka-server-net:
    driver: bridge
  psup-shared-net:
    external: true